### ISSUE TITLE
How to reproduce the result on ESC50?

### ISSUE THREAD

**Issue by mlxu995** [FunAudioLLM/SenseVoice#67]
I used it to test the ESC50 dataset and excepted the same results as mentioned in the readme file.
I used the following test code, but could not reproduce the results.

```
m, kwargs = SenseVoiceSmall.from_pretrained(model='iic/SenseVoiceSmall', device='cuda:0')
res = m.inference(
    data_in=os.path.join(audio_path),
    language="nospeech",
    use_itn=False,
    **kwargs,
)
```

Look forward to your guidance.

**Comment by gaochangfeng** [comment]
Can you show the your precision and recall score results? If the difference is significant, the reason is that:
With default decoding configuration, the precision is always much larger than the recall so the F1 score will become low. We modificate the posterior probability for the event as follow (additional, in our experiments, language="auto"):
```
        # c. Passed the encoder result and the beam search
        ctc_logits = self.ctc.log_softmax(encoder_out)
        if kwargs.get("ban_emo_unk", False):
            ctc_logits[:, :, self.emo_dict["unk"]] = -float("inf")

        event_list = [24993, 24995, 24997, 24999, 25010, 25011, 25012, 25013, 25014] # Speech, BGM, Laughter, Applause, Cry, Sneeze, Breath, Cough, Sing
        event_gain = [1e-9, 1e-9, 1, 10, 3, 3, 1, 3, 1e-9]
        import math
        for pos, ga in zip(event_list, event_gain):
            ctc_logits[:, :, pos] += math.log(ga)
```
However, unlike PANNs or BEATs, the events are conflicting with each other so they cannot rich the best result at the same time.

**Comment by mlxu995** [comment]
Thanks, I tried to manually modify the posterior probability and get F1 scores similar to the official result.
